import React from 'react';

interface SlideItem {
  title: string;
  summary: string;
  bullets: string[];
  imagePrompt: string;
  imageUrl?: string;
}

async function fetchToDataUrl(url: string): Promise<string | null> {
  if (!url) return null;
  if (url.startsWith('data:')) return url;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch (e) {
    console.error('[pdfExporter] Failed to fetch image to data URL:', e);
    return null;
  }
}

export async function exportToPDF(
  title: string,
  slides: SlideItem[],
  theme: 'dark' | 'light' | 'gradient' | 'corporate'
) {
  // Dynamically import react-pdf to keep bundle lightweight
  const { Document, Page, Text, View, Image, StyleSheet, pdf } = await import('@react-pdf/renderer');

  const isDark = theme === 'dark' || theme === 'gradient';
  
  const bgColor = theme === 'dark' 
    ? '#140D16' 
    : theme === 'gradient'
    ? '#0D0914'
    : theme === 'corporate'
    ? '#FAFAFA'
    : '#FFFFFF';
  
  const textColor = isDark ? '#FFFFFF' : '#18181B';
  const textMutedColor = isDark ? '#A1A1AA' : '#71717A';
  const accentColor = '#DE36F5'; // Fuchsia

  // Pre-fetch remote images to base64 data URLs
  const slideImageMap = new Map<number, string>();
  await Promise.all(
    slides.map(async (slide, idx) => {
      if (slide.imageUrl) {
        const dataUrl = await fetchToDataUrl(slide.imageUrl);
        if (dataUrl) {
          slideImageMap.set(idx, dataUrl);
        }
      }
    })
  );

  const styles = StyleSheet.create({
    page: {
      flexDirection: 'column',
      backgroundColor: bgColor,
      color: textColor,
      padding: 40,
      fontFamily: 'Helvetica',
      height: '100%'
    },
    // Title Slide
    titleContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      height: '100%'
    },
    mainTitle: {
      fontSize: 36,
      fontWeight: 'bold',
      marginBottom: 15,
      textAlign: 'center'
    },
    subtitle: {
      fontSize: 14,
      color: textMutedColor,
      textAlign: 'center'
    },
    // Content Slides
    header: {
      fontSize: 22,
      fontWeight: 'bold',
      color: accentColor,
      marginBottom: 20,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? '#27272A' : '#E4E4E7',
      paddingBottom: 10
    },
    contentRow: {
      flexDirection: 'row',
      flex: 1,
      gap: 20
    },
    bulletsCol: {
      flex: 1,
      flexDirection: 'column',
      gap: 12
    },
    bulletItem: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8
    },
    bulletDot: {
      fontSize: 14,
      color: accentColor
    },
    bulletText: {
      fontSize: 12,
      lineHeight: 1.5,
      flex: 1
    },
    imageCol: {
      width: '45%',
      height: 200,
      borderRadius: 8,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: isDark ? '#27272A' : '#E4E4E7'
    },
    footer: {
      marginTop: 'auto',
      paddingTop: 15,
      borderTopWidth: 1,
      borderTopColor: isDark ? '#27272A' : '#E4E4E7',
      flexDirection: 'row',
      justifyContent: 'space-between'
    },
    footerText: {
      fontSize: 8,
      color: textMutedColor
    }
  });

  const MyDocument = () => (
    <Document>
      {/* 1. Title Slide */}
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.titleContainer}>
          <Text style={styles.mainTitle}>{title}</Text>
          <Text style={styles.subtitle}>Generated by Cybrdeck Studio</Text>
        </View>
      </Page>

      {/* 2. Content Slides */}
      {slides.map((slide, index) => {
        const imageDataUrl = slideImageMap.get(index);
        return (
          <Page key={index} size="A4" orientation="landscape" style={styles.page}>
            <Text style={styles.header}>{slide.title}</Text>

            <View style={styles.contentRow}>
              {/* Left Column - Bullets */}
              <View style={styles.bulletsCol}>
                {slide.bullets.map((bullet, bIdx) => (
                  <View key={bIdx} style={styles.bulletItem}>
                    <Text style={styles.bulletDot}>•</Text>
                    <Text style={styles.bulletText}>{bullet}</Text>
                  </View>
                ))}
              </View>

              {/* Right Column - Image (if exists) */}
              {imageDataUrl ? (
                <View style={styles.imageCol}>
                  <Image src={imageDataUrl} aria-hidden style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                </View>
              ) : null}
            </View>

            {/* Footer */}
            <View style={styles.footer}>
              <Text style={styles.footerText}>{title}</Text>
              <Text style={styles.footerText}>Slide {index + 2}</Text>
            </View>
          </Page>
        );
      })}
    </Document>
  );

  // Generate PDF Blob
  const blob = await pdf(<MyDocument />).toBlob();
  const blobUrl = URL.createObjectURL(blob);
  
  // Download file
  const a = document.createElement('a');
  a.href = blobUrl;
  a.download = `${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${Date.now()}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(blobUrl);
}
