import pptxgen from 'pptxgenjs';

interface SlideItem {
  title: string;
  summary: string;
  bullets: string[];
  imagePrompt: string;
  imageUrl?: string;
}

async function fetchToDataUrl(url: string): Promise<string | null> {
  if (!url) return null;
  if (url.startsWith('data:')) return url;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch (e) {
    console.error('[pptxExporter] Failed to fetch image to data URL:', e);
    return null;
  }
}

export async function exportToPPTX(
  title: string,
  slides: SlideItem[],
  theme: 'dark' | 'light' | 'gradient' | 'corporate'
) {
  const pres = new pptxgen();

  // Set presentation layout to 16:9 widescreen
  pres.layout = 'LAYOUT_16x9';

  const isDark = theme === 'dark' || theme === 'gradient';
  const bgColor = theme === 'dark' 
    ? '140D16' 
    : theme === 'gradient'
    ? '0D0914'
    : theme === 'corporate'
    ? 'FAFAFA'
    : 'FFFFFF';
  
  const textColor = isDark ? 'FFFFFF' : '18181B';
  const accentColor = 'DE36F5'; // Cybrdeck Fuchsia

  // Pre-fetch images to base64 data URLs
  const slideImageMap = new Map<number, string>();
  await Promise.all(
    slides.map(async (slide, idx) => {
      if (slide.imageUrl) {
        const dataUrl = await fetchToDataUrl(slide.imageUrl);
        if (dataUrl) {
          slideImageMap.set(idx, dataUrl);
        }
      }
    })
  );

  // 1. Create Title Slide
  const titleSlide = pres.addSlide();
  titleSlide.background = { fill: bgColor };
  titleSlide.addText(title, {
    x: 1.0,
    y: 2.2,
    w: 8.0,
    h: 1.5,
    fontSize: 40,
    bold: true,
    color: textColor,
    fontFace: 'Arial'
  });
  titleSlide.addText('Generated by Cybrdeck Studio', {
    x: 1.0,
    y: 3.8,
    w: 8.0,
    h: 0.5,
    fontSize: 14,
    color: isDark ? 'A1A1AA' : '71717A',
    fontFace: 'Arial'
  });

  // 2. Add content slides
  slides.forEach((slide, idx) => {
    const slideObj = pres.addSlide();
    slideObj.background = { fill: bgColor };

    // Slide Header
    slideObj.addText(slide.title, {
      x: 0.8,
      y: 0.5,
      w: 8.4,
      h: 0.8,
      fontSize: 24,
      bold: true,
      color: accentColor,
      fontFace: 'Arial'
    });

    const imageDataUrl = slideImageMap.get(idx);

    // Determine layout: check if image exists
    if (imageDataUrl) {
      // Left side text
      slideObj.addText(slide.bullets.map(b => `• ${b}`).join('\n\n'), {
        x: 0.8,
        y: 1.5,
        w: 4.8,
        h: 3.5,
        fontSize: 13,
        color: textColor,
        fontFace: 'Arial',
        valign: 'top',
        align: 'left'
      });

      // Right side image
      slideObj.addImage({
        data: imageDataUrl,
        x: 6.0,
        y: 1.5,
        w: 3.2,
        h: 2.4
      });
    } else {
      // Full width text
      slideObj.addText(slide.bullets.map(b => `• ${b}`).join('\n\n'), {
        x: 0.8,
        y: 1.5,
        w: 8.4,
        h: 3.5,
        fontSize: 14,
        color: textColor,
        fontFace: 'Arial',
        valign: 'top',
        align: 'left'
      });
    }

    // Small footer on slides
    slideObj.addText(title, {
      x: 0.8,
      y: 5.1,
      w: 5.0,
      h: 0.3,
      fontSize: 8,
      color: isDark ? '52525B' : 'A1A1AA',
      fontFace: 'Arial'
    });
  });

  // Save the presentation file
  const fileName = `${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${Date.now()}.pptx`;
  await pres.writeFile({ fileName });
}
