'use client';

import { useState } from 'react';
import { Icon } from '@/components/ui/icon';

import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import type { PlaygroundStreamSendOptions } from '@/lib/playground/hooks/usePlaygroundStream';

export interface GetCodeModalProps {
    open: boolean;
    onOpenChange(open: boolean): void;
    modelId: string;
    modelDisplayName?: string;
    prompt: string;
    options: PlaygroundStreamSendOptions;
    conversationHistory?: Array<{ role: string; content: string }>;
}

export function GetCodeModal({
    open,
    onOpenChange,
    modelId,
    modelDisplayName,
    prompt,
    options,
    conversationHistory = [],
}: GetCodeModalProps) {
    const [copiedFormat, setCopiedFormat] = useState<string | null>(null);

    const displayName = modelDisplayName || modelId;

    // 1. Build clean Markdown document
    const markdownContent = [
        `# ${displayName} - Generation Output`,
        `**Model ID:** \`${modelId}\``,
        options.systemPrompt ? `**System Persona:** ${options.systemPrompt}` : null,
        `**Temperature:** ${options.temperature ?? 0.7} | **Top P:** ${options.topP ?? 0.95} | **Max Tokens:** ${options.maxTokens ?? 4096}`,
        `---`,
        `## Prompt`,
        prompt || '*(No prompt recorded)*',
        `---`,
        `## Output / Conversation History`,
        conversationHistory.length > 0
            ? conversationHistory.map(m => `### ${m.role.toUpperCase()}\n${m.content}`).join('\n\n')
            : '*(No conversation history recorded yet)*',
    ].filter(Boolean).join('\n\n');

    // 2. Build simple clean Python code snippet (No Firebase hassle).
    // The host is resolved from the current window so the snippet works on
    // preview deployments and local dev instead of always pointing at prod
    // (audit #20). The Authorization header is included as a placeholder —
    // the stream route 401s without a Firebase ID token (audit #21).
    const origin = typeof window !== 'undefined' ? window.location.origin : 'https://cybrdeck.com';
    const pythonCode = [
        `# Reproduce run via standard HTTP POST`,
        `import requests`,
        ``,
        `# Replace with your Firebase ID token (see /docs/api-auth).`,
        `# Guests omit the header and rely on the __pg_guest fingerprint cookie.`,
        `API_TOKEN = "YOUR_FIREBASE_ID_TOKEN"`,
        ``,
        `url = "${origin}/api/playground/stream/${modelId}"`,
        `payload = {`,
        `    "modelId": "${modelId}",`,
        `    "prompt": ${JSON.stringify(prompt || 'Your prompt here')},`,
        options.systemPrompt ? `    "systemPrompt": ${JSON.stringify(options.systemPrompt)},` : null,
        `    "temperature": ${options.temperature ?? 0.7},`,
        `    "maxTokens": ${options.maxTokens ?? 4096}`,
        `}`,
        `headers = {"Authorization": f"Bearer {API_TOKEN}"}`,
        ``,
        `response = requests.post(url, json=payload, headers=headers, stream=True)`,
        `response.raise_for_status()`,
        `for line in response.iter_lines(decode_unicode=True):`,
        `    if line and line.startswith("data:"):`,
        `        print(line[5:], end="", flush=True)`,
    ].filter(Boolean).join('\n');

    const handleCopyMarkdown = async () => {
        try {
            await navigator.clipboard.writeText(markdownContent);
            setCopiedFormat('md');
            setTimeout(() => setCopiedFormat(null), 2000);
        } catch (err) {
            console.error('Failed to copy: ', err);
        }
    };

    const handleCopyCode = async () => {
        try {
            await navigator.clipboard.writeText(pythonCode);
            setCopiedFormat('code');
            setTimeout(() => setCopiedFormat(null), 2000);
        } catch (err) {
            console.error('Failed to copy code: ', err);
        }
    };

    const handleDownloadMd = () => {
        const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.setAttribute('download', `${modelId}-output.md`);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    const cursorRulesSnippet = `# Project Guidelines & Agent Rules\n# Generated by Cybrdeck Studio\n\n- Primary Language: TypeScript / React\n- Styling: Tailwind CSS\n- Code Quality: Production ready, zero fluff, clean error handling.\n- Model context: Initial prototype generated using ${displayName}.\n\n## Initial Prompt\n${prompt || 'No prompt provided'}`;

    const handleCopyCursorRules = async () => {
        try {
            await navigator.clipboard.writeText(cursorRulesSnippet);
            setCopiedFormat('rules');
            setTimeout(() => setCopiedFormat(null), 2000);
        } catch (err) {
            console.error('Failed to copy rules: ', err);
        }
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="max-w-2xl bg-zinc-950/95 border-white/15 text-white backdrop-blur-2xl">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2 text-lg font-bold text-brand-400">
                        <Icon name="file-document" className="h-5 w-5" /> Export & Migrate to External IDE
                    </DialogTitle>
                    <DialogDescription className="text-xs text-zinc-400">
                        Export prototype code, download documentation, or copy IDE instructions for <span className="font-semibold text-white">Cursor, Antigravity, Windsurf, Qoder, Codex, or Claude</span>.
                    </DialogDescription>
                </DialogHeader>

                <div className="space-y-4 pt-2">
                    {/* Action buttons bar */}
                    <div className="grid grid-cols-3 gap-2.5">
                        <Button
                            type="button"
                            onClick={handleDownloadMd}
                            className="h-10 bg-brand-600 hover:bg-brand-500 text-white font-semibold flex items-center justify-center gap-2 text-xs shadow-lg"
                        >
                            <Icon name="download" className="h-4 w-4" />
                            <span>Download .md</span>
                        </Button>

                        <Button
                            type="button"
                            variant="outline"
                            onClick={handleCopyMarkdown}
                            className="h-10 border-white/20 bg-white/5 hover:bg-white/10 text-white font-semibold flex items-center justify-center gap-2 text-xs"
                        >
                            {copiedFormat === 'md' ? (
                                <>
                                    <Icon name="check" className="h-4 w-4 text-emerald-400" />
                                    <span>Copied MD!</span>
                                </>
                            ) : (
                                <>
                                    <Icon name="copy" className="h-4 w-4 text-brand-400" />
                                    <span>Copy Markdown</span>
                                </>
                            )}
                        </Button>

                        <Button
                            type="button"
                            variant="outline"
                            onClick={handleCopyCursorRules}
                            className="h-10 border-amber-500/30 bg-amber-500/10 hover:bg-amber-500/20 text-amber-300 font-semibold flex items-center justify-center gap-2 text-xs"
                        >
                            {copiedFormat === 'rules' ? (
                                <>
                                    <Icon name="check" className="h-4 w-4 text-emerald-400" />
                                    <span>Copied Rules!</span>
                                </>
                            ) : (
                                <>
                                    <Icon name="code" className="h-4 w-4 text-amber-400" />
                                    <span>Copy .cursorrules</span>
                                </>
                            )}
                        </Button>
                    </div>

                    {/* Python integration code snippet preview */}
                    <div className="space-y-1.5">
                        <div className="flex items-center justify-between">
                            <span className="text-[10px] font-bold uppercase tracking-wider text-brand-400 flex items-center gap-1">
                                <Icon name="code" className="h-3 w-3" /> Execution & Migration Snippet
                            </span>
                            <button
                                type="button"
                                onClick={handleCopyCode}
                                className="text-[10px] text-zinc-400 hover:text-white flex items-center gap-1 font-mono"
                            >
                                {copiedFormat === 'code' ? <Icon name="check" className="h-3 w-3 text-emerald-400" /> : <Icon name="copy" className="h-3 w-3" />}
                                {copiedFormat === 'code' ? 'Copied' : 'Copy Snippet'}
                            </button>
                        </div>
                        <pre className="custom-scrollbar max-h-40 overflow-auto rounded-lg border border-white/15 bg-black/50 p-3 font-mono text-[11px] leading-relaxed text-zinc-200">
                            {pythonCode}
                        </pre>
                    </div>
                </div>
            </DialogContent>
        </Dialog>
    );
}
